// 실제 데이터 기반 시드 데이터
// 출처: 계약서 목록 2025.xlsx, 계약현황 Excel(2019-2024), 견적서 파일명(2019-2026)

// === JSON 데이터 타입 ===
interface RawContract {
  year: number;
  company: string;
  service: string;
  contract_amount: number;
  notes: string;
  payments: Array<{
    invoice_date: string;
    invoice_amount: number;
    payment_date: string;
    payment_amount: number;
  }>;
  total_invoiced: number;
  total_received: number;
  outstanding_invoiced: number;
  uninvoiced: number;
}

interface RawQuote {
  quote_number: string;
  year: number;
  month: number;
  company: string;
  service: string;
  file_name: string;
  file_path: string;
  grand_total?: number;
  total_amount?: number;
  vat_amount?: number;
}

// === JSON 데이터 로드 (esbuild가 번들링) ===
const allContractsRaw: RawContract[] = require('./allContracts.json');
const allQuotesRaw: RawQuote[] = require('./allQuotes.json');

// ================================================================
// 견적서 데이터
// ================================================================
export function getSampleQuotes(companyId: string) {
  // 2025년 수작업 견적서 (금액 포함)
  const handcraftedQuotes = [
    {
      company_id: companyId,
      quote_number: 'ECA-2505-1',
      recipient_company: '(주)해안종합건축사사무소',
      recipient_contact: '',
      recipient_phone: '',
      recipient_email: '',
      title: '광명시흥 B1-3, S1-10BL 민간참여 공동주택 친환경 컨설팅',
      service_name: '광명시흥 B1-3, S1-10BL 민간참여 공동주택 친환경 컨설팅',
      labor_total: 55000000,
      expense_total: 15000000,
      total_amount: 70000000,
      vat_amount: 7000000,
      grand_total: 77000000,
      status: 'converted',
      quote_date: '2025-05-10',
      valid_until: '2025-06-10',
      notes: 'AA25-30 계약 전환 (공모)',
      created_by: null,
    },
    {
      company_id: companyId,
      quote_number: 'ECA-2505-2',
      recipient_company: '(주)해안종합건축사사무소',
      recipient_contact: '',
      recipient_phone: '',
      recipient_email: '',
      title: '광명시흥 B1-3, S1-10BL 민간참여 공동주택 (수수료 포함)',
      service_name: '광명시흥 B1-3, S1-10BL 민간참여 공동주택 친환경+교육환경 컨설팅',
      labor_total: 170000000,
      expense_total: 35000000,
      total_amount: 205000000,
      vat_amount: 20500000,
      grand_total: 225500000,
      status: 'converted',
      quote_date: '2025-05-12',
      valid_until: '2025-06-12',
      notes: 'AA25-31 계약 전환 (실시), 수수료 포함 버전',
      created_by: null,
    },
    {
      company_id: companyId,
      quote_number: 'ECA-2506-3',
      recipient_company: '(주)해마종합건축사사무소',
      recipient_contact: '',
      recipient_phone: '',
      recipient_email: '',
      title: '의왕군포안산 S1-1, S1-3BL 민간참여 공동주택',
      service_name: '의왕군포안산 S1-1, S1-3BL 민간참여 공공주택사업 친환경 컨설팅',
      labor_total: 130000000,
      expense_total: 28437785,
      total_amount: 158437785,
      vat_amount: 15843779,
      grand_total: 174281564,
      status: 'converted',
      quote_date: '2025-06-05',
      valid_until: '2025-07-05',
      notes: 'AA25-26(공모), AA25-27(실시) 계약 전환',
      created_by: null,
    },
    {
      company_id: companyId,
      quote_number: 'ECA-2507-4',
      recipient_company: '(주)토문엔지니어링건축사사무소',
      recipient_contact: '',
      recipient_phone: '',
      recipient_email: '',
      title: '행정중심복합도시 52L2, 52M2BL 공동주택',
      service_name: '행정중심복합도시 52L2, 52M2BL 공동주택 친환경 컨설팅',
      labor_total: 35000000,
      expense_total: 10000000,
      total_amount: 45000000,
      vat_amount: 4500000,
      grand_total: 49500000,
      status: 'submitted',
      quote_date: '2025-07-15',
      valid_until: '2025-08-15',
      notes: '승인 진행중',
      created_by: null,
    },
    {
      company_id: companyId,
      quote_number: 'ECA-2508-5',
      recipient_company: '희림종합건축사사무소',
      recipient_contact: '',
      recipient_phone: '',
      recipient_email: '',
      title: '검단신도시 AA17블록 중흥에스클래스 친환경+교육환경',
      service_name: '검단신도시 AA17블록 중흥에스클래스 친환경+교육환경 컨설팅',
      labor_total: 48000000,
      expense_total: 11670000,
      total_amount: 59670000,
      vat_amount: 5967000,
      grand_total: 65637000,
      status: 'draft',
      quote_date: '2025-08-20',
      valid_until: '2025-09-20',
      notes: '친환경 36,720,000 + 교육환경 22,950,000',
      created_by: null,
    },
  ];

  // JSON 파일에서 2019~2026 견적서 변환
  const historicalQuotes = allQuotesRaw.map(q => {
    const recipientCompany = q.service ? q.company : '';
    const serviceName = q.service || q.company;
    const month = Math.min(q.month, 12);
    const nextMonth = month < 12 ? month + 1 : 12;

    return {
      company_id: companyId,
      quote_number: q.quote_number,
      recipient_company: recipientCompany,
      recipient_contact: '',
      recipient_phone: '',
      recipient_email: '',
      title: serviceName,
      service_name: serviceName,
      labor_total: 0,
      expense_total: 0,
      total_amount: q.total_amount || 0,
      vat_amount: q.vat_amount || 0,
      grand_total: q.grand_total || 0,
      status: q.year <= 2023 ? 'converted' : q.year === 2024 ? 'submitted' : 'draft',
      quote_date: `${q.year}-${String(month).padStart(2, '0')}-01`,
      valid_until: `${q.year}-${String(nextMonth).padStart(2, '0')}-28`,
      notes: `파일: ${q.file_name}`,
      source_file_path: q.file_path || null,
      created_by: null,
    };
  });

  return [...handcraftedQuotes, ...historicalQuotes];
}

// ================================================================
// 계약서 데이터
// ================================================================
export function getSampleContracts(companyId: string) {
  // 2025년 수작업 계약서 (42건, AA25/AB25/BB25 번호 체계)
  const contracts2025 = [
    {
      company_id: companyId,
      contract_number: 'AA25-01',
      contract_code: 'AA25-01',
      client_company: '범도시건축',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '남양주왕숙 A-25BL 민간참여 공공주택 친환경 컨설팅',
      description: '남양주왕숙 A-25BL 민간참여 공공주택사업 친환경인증 컨설팅',
      contract_start_date: '2024-09-01',
      contract_end_date: '2025-12-31',
      contract_amount: 27000000,
      vat_amount: 2700000,
      total_amount: 29700000,
      received_amount: 13200000,
      remaining_amount: 16500000,
      progress: 'in_progress',
      progress_note: '승인(완)/변경승인 진행중',
      notes: '범도시/무영/천진건축 공동 프로젝트',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-02',
      contract_code: 'AA25-02',
      client_company: '㈜범도시건축종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '남양주왕숙 A25BL 민간참여 공공주택 건설사업',
      description: '범도시/무영/천진 공동 (공모 부분 포함)',
      contract_start_date: '2025-02-01',
      contract_end_date: '2026-01-31',
      contract_amount: 63000000,
      vat_amount: 0,
      total_amount: 63000000,
      received_amount: 0,
      remaining_amount: 63000000,
      progress: 'in_progress',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-03',
      contract_code: 'AA25-03',
      client_company: '㈜성현종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '의왕청계2 A-3BL 설계용역(재설계)',
      description: '',
      contract_start_date: '2024-12-01',
      contract_end_date: '2025-11-30',
      contract_amount: 27000000,
      vat_amount: 0,
      total_amount: 27000000,
      received_amount: 0,
      remaining_amount: 27000000,
      progress: 'in_progress',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-04',
      contract_code: 'AA25-04',
      client_company: '디엘이앤씨 주식회사',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: 'ZEB 신재생에너지 개산견적 가이드 작성 ECO2 시뮬레이션 용역',
      description: '',
      contract_start_date: '2025-03-01',
      contract_end_date: '2025-12-31',
      contract_amount: 30000000,
      vat_amount: 3000000,
      total_amount: 33000000,
      received_amount: 33000000,
      remaining_amount: 0,
      progress: 'completed',
      progress_note: 'VAT 별도 / 완료',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-05',
      contract_code: 'AA25-05',
      client_company: '㈜해안종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '실버스테이 시범사업 민간사업자 공모(구리갈매)',
      description: '',
      contract_start_date: '2025-04-01',
      contract_end_date: '2026-03-31',
      contract_amount: 9000000,
      vat_amount: 900000,
      total_amount: 9900000,
      received_amount: 0,
      remaining_amount: 9900000,
      progress: 'in_progress',
      progress_note: 'VAT 별도',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-06',
      contract_code: 'AA25-06',
      client_company: '주식회사 에스아이그룹건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '남양주왕숙 A6BL 공동주택 설계용역 친환경 컨설팅',
      description: '에스아이건축 남양주왕숙 A6BL 공동주택 설계용역 / 인건비 별도관리',
      contract_start_date: '2025-04-01',
      contract_end_date: '2026-03-31',
      contract_amount: 92000000,
      vat_amount: 0,
      total_amount: 92000000,
      received_amount: 27600000,
      remaining_amount: 64400000,
      progress: 'in_progress',
      progress_note: '승인 진행중 / VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-07',
      contract_code: 'AA25-07',
      client_company: '㈜유선엔지니어링건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '인천검단 AA13-2블록 공공주택건설사업 설계용역',
      description: '변경사업승인',
      contract_start_date: '2025-05-01',
      contract_end_date: '2026-04-30',
      contract_amount: 24000000,
      vat_amount: 0,
      total_amount: 24000000,
      received_amount: 0,
      remaining_amount: 24000000,
      progress: 'in_progress',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-08',
      contract_code: 'AA25-08',
      client_company: '(주)구성이엔드씨',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '통합배관 적용 가능성 검증 ECO2 분석 용역',
      description: '증액건, 원계약 2019',
      contract_start_date: '2025-05-01',
      contract_end_date: '2025-12-31',
      contract_amount: 20000000,
      vat_amount: 0,
      total_amount: 20000000,
      received_amount: 20000000,
      remaining_amount: 0,
      progress: 'completed',
      progress_note: '완료',
      notes: '증액건, 원계약 2019',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-09',
      contract_code: 'AA25-09',
      client_company: '㈜유선엔지니어링건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '인천검단 AA13-2블록 공공주택건설사업 설계용역(변경사업승인)',
      description: '',
      contract_start_date: '2025-06-01',
      contract_end_date: '2026-05-31',
      contract_amount: 22000000,
      vat_amount: 0,
      total_amount: 22000000,
      received_amount: 0,
      remaining_amount: 22000000,
      progress: 'in_progress',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-10',
      contract_code: 'AA25-10',
      client_company: '(주)구성이엔드씨',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '통합배관 적용 가능성 검증 ECO2 분석 용역(화성능동 B1, 인천가정2 A1BL)',
      description: '',
      contract_start_date: '2025-06-01',
      contract_end_date: '2025-12-31',
      contract_amount: 5000000,
      vat_amount: 500000,
      total_amount: 5500000,
      received_amount: 5500000,
      remaining_amount: 0,
      progress: 'completed',
      progress_note: 'VAT 별도 / 완료',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-11',
      contract_code: 'AA25-11',
      client_company: '(주)경동나비엔',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '통합배관 적용 가능성 검증 ECO2 분석 용역(화성능동 B1, 인천가정2 A1BL)',
      description: '',
      contract_start_date: '2025-07-01',
      contract_end_date: '2025-12-31',
      contract_amount: 5000000,
      vat_amount: 500000,
      total_amount: 5500000,
      received_amount: 5500000,
      remaining_amount: 0,
      progress: 'completed',
      progress_note: 'VAT 별도 / 완료',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-12',
      contract_code: 'AA25-12',
      client_company: '(주)해마종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '인천검단 AA26BL 공공지원 민간임대 친환경 컨설팅',
      description: '',
      contract_start_date: '2025-07-01',
      contract_end_date: '2026-06-30',
      contract_amount: 80000000,
      vat_amount: 0,
      total_amount: 80000000,
      received_amount: 0,
      remaining_amount: 80000000,
      progress: 'contract_signed',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-13',
      contract_code: 'AA25-13',
      client_company: '(주)디에이그룹엔지니어링종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '남양주 왕숙 A-17, S-18BL 민간참여 친환경+교육환경 컨설팅',
      description: '디에이건축/길건축 공동 프로젝트',
      contract_start_date: '2025-07-01',
      contract_end_date: '2026-12-31',
      contract_amount: 250000000,
      vat_amount: 0,
      total_amount: 250000000,
      received_amount: 25000000,
      remaining_amount: 225000000,
      progress: 'in_progress',
      progress_note: 'VAT 포함 / 디에이 102,000,000 + 길건축 51,000,000 + 기타',
      notes: '2025년 최대 규모 계약',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-14',
      contract_code: 'AA25-14',
      client_company: '건일엠이씨(해안)',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '고양창릉 S-9BL 공동주택 설계용역 친환경 컨설팅',
      description: '',
      contract_start_date: '2025-08-01',
      contract_end_date: '2026-07-31',
      contract_amount: 108000000,
      vat_amount: 10800000,
      total_amount: 118800000,
      received_amount: 0,
      remaining_amount: 118800000,
      progress: 'in_progress',
      progress_note: '승인 진행중 / VAT 별도',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-15',
      contract_code: 'AA25-15',
      client_company: '㈜마메종',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '울산대공원 한신더휴 친환경 컨설팅',
      description: '',
      contract_start_date: '2025-08-01',
      contract_end_date: '2026-07-31',
      contract_amount: 38000000,
      vat_amount: 0,
      total_amount: 38000000,
      received_amount: 0,
      remaining_amount: 38000000,
      progress: 'in_progress',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-16',
      contract_code: 'AA25-16',
      client_company: '㈜지엔엠건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '울산선바위 S-5BL 공동주택 설계용역',
      description: '지엔엠/행림/에스아이 공동',
      contract_start_date: '2025-08-01',
      contract_end_date: '2026-07-31',
      contract_amount: 143750000,
      vat_amount: 0,
      total_amount: 143750000,
      received_amount: 0,
      remaining_amount: 143750000,
      progress: 'in_progress',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-17',
      contract_code: 'AA25-17',
      client_company: '㈜케이디엔지니어링건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '대전죽동2 A-2BL 공동주택 친환경 설계용역',
      description: '케이디/다인 공동',
      contract_start_date: '2025-08-01',
      contract_end_date: '2026-07-31',
      contract_amount: 90000000,
      vat_amount: 0,
      total_amount: 90000000,
      received_amount: 0,
      remaining_amount: 90000000,
      progress: 'in_progress',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-18',
      contract_code: 'AA25-18',
      client_company: '㈜에스아이그룹건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '남양주왕숙 PM-3BL 및 남양주왕숙2 A-1BL 민간참여 공공주택건설사업',
      description: '에스아이/에스파스/두올 공동',
      contract_start_date: '2025-09-01',
      contract_end_date: '2026-08-31',
      contract_amount: 30000000,
      vat_amount: 0,
      total_amount: 30000000,
      received_amount: 0,
      remaining_amount: 30000000,
      progress: 'in_progress',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-19',
      contract_code: 'AA25-19',
      client_company: '다솜/성일건설',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '증액분 (다솜/성일 친환경 컨설팅)',
      description: '다솜 증액분 3,928,000 / 성일 증액분 24,072,000',
      contract_start_date: '2025-09-01',
      contract_end_date: '2026-08-31',
      contract_amount: 28000000,
      vat_amount: 0,
      total_amount: 28000000,
      received_amount: 0,
      remaining_amount: 28000000,
      progress: 'in_progress',
      progress_note: '증액건',
      notes: '다솜 증액분 3,928,000 / 성일 증액분 24,072,000',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-20',
      contract_code: 'AA25-20',
      client_company: '㈜지엔엠건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '울산선바위 A-5BL 공동주택 설계용역',
      description: '지엔엠/선진/에스아이/디엔비 공동',
      contract_start_date: '2025-09-01',
      contract_end_date: '2026-08-31',
      contract_amount: 120750000,
      vat_amount: 0,
      total_amount: 120750000,
      received_amount: 0,
      remaining_amount: 120750000,
      progress: 'in_progress',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-21',
      contract_code: 'AA25-21',
      client_company: '㈜지엔엠건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '울산선바위 A-6BL 공동주택 설계용역',
      description: '지엔엠/선진/에스아이/디엔비 공동',
      contract_start_date: '2025-09-01',
      contract_end_date: '2026-08-31',
      contract_amount: 74750000,
      vat_amount: 0,
      total_amount: 74750000,
      received_amount: 0,
      remaining_amount: 74750000,
      progress: 'in_progress',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-22',
      contract_code: 'AA25-22',
      client_company: '에이앤유디자인그룹건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '여수죽림 A7블록 친환경(교육)분야 컨설팅',
      description: '에이앤유/운주건축 공동',
      contract_start_date: '2025-09-01',
      contract_end_date: '2026-08-31',
      contract_amount: 75000000,
      vat_amount: 0,
      total_amount: 75000000,
      received_amount: 33200000,
      remaining_amount: 41800000,
      progress: 'in_progress',
      progress_note: '승인(완) / VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-23',
      contract_code: 'AA25-23',
      client_company: '㈜해안종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '실버스테이 시범사업(구리갈매) 교육환경영향평가',
      description: '',
      contract_start_date: '2025-09-01',
      contract_end_date: '2026-08-31',
      contract_amount: 70000000,
      vat_amount: 0,
      total_amount: 70000000,
      received_amount: 0,
      remaining_amount: 70000000,
      progress: 'contract_signed',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-24',
      contract_code: 'AA25-24',
      client_company: '㈜건축사사무소 에스파스',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '의왕군포안산 S1-1, S1-3BL 공공주택건립사업(기술제안)',
      description: '',
      contract_start_date: '2025-09-01',
      contract_end_date: '2026-08-31',
      contract_amount: 10502888,
      vat_amount: 0,
      total_amount: 10502888,
      received_amount: 0,
      remaining_amount: 10502888,
      progress: 'contract_signed',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-25',
      contract_code: 'AA25-25',
      client_company: '㈜건축사사무소 에스파스',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '의왕군포안산 S1-1, S1-3BL 공공주택건립사업(실시설계)',
      description: '',
      contract_start_date: '2025-09-01',
      contract_end_date: '2027-08-31',
      contract_amount: 68718892,
      vat_amount: 0,
      total_amount: 68718892,
      received_amount: 0,
      remaining_amount: 68718892,
      progress: 'contract_signed',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-26',
      contract_code: 'AA25-26',
      client_company: '(주)해마종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '의왕군포안산 S1-1, S1-3BL 민간참여 공공주택사업(공모)',
      description: '견적서 ECA-2506-3에서 계약 전환 (공모 부분)',
      contract_start_date: '2025-09-01',
      contract_end_date: '2026-08-31',
      contract_amount: 21005775,
      vat_amount: 2100578,
      total_amount: 23106353,
      received_amount: 0,
      remaining_amount: 23106353,
      progress: 'contract_signed',
      progress_note: 'VAT 별도',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-27',
      contract_code: 'AA25-27',
      client_company: '(주)해마종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '의왕군포안산 S1-1, S1-3BL 민간참여 공공주택사업(실시)',
      description: '견적서 ECA-2506-3에서 계약 전환 (실시 부분)',
      contract_start_date: '2025-09-01',
      contract_end_date: '2027-08-31',
      contract_amount: 137437785,
      vat_amount: 13743779,
      total_amount: 151181564,
      received_amount: 0,
      remaining_amount: 151181564,
      progress: 'contract_signed',
      progress_note: 'VAT 별도',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-28',
      contract_code: 'AA25-28',
      client_company: '㈜인보건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '의왕군포안산 S1-1, S1-3 민간참여 공공주택건설사업(공모)',
      description: '',
      contract_start_date: '2025-10-01',
      contract_end_date: '2026-09-30',
      contract_amount: 3500962,
      vat_amount: 0,
      total_amount: 3500962,
      received_amount: 0,
      remaining_amount: 3500962,
      progress: 'contract_signed',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-29',
      contract_code: 'AA25-29',
      client_company: '㈜인보건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '의왕군포안산 S1-1, S1-3 민간참여 공공주택건설사업(실시)',
      description: '',
      contract_start_date: '2025-10-01',
      contract_end_date: '2027-09-30',
      contract_amount: 22906297,
      vat_amount: 0,
      total_amount: 22906297,
      received_amount: 0,
      remaining_amount: 22906297,
      progress: 'contract_signed',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-30',
      contract_code: 'AA25-30',
      client_company: '(주)해안종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '광명시흥 B1-3, S1-10BL 민간참여 공공주택사업(공모)',
      description: '해안,행림,피에이씨 공동 / 견적서 ECA-2505-1에서 전환',
      contract_start_date: '2025-10-01',
      contract_end_date: '2026-09-30',
      contract_amount: 70000000,
      vat_amount: 7000000,
      total_amount: 77000000,
      received_amount: 0,
      remaining_amount: 77000000,
      progress: 'in_progress',
      progress_note: '승인 진행중 / VAT 별도',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-31',
      contract_code: 'AA25-31',
      client_company: '(주)해안종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '광명시흥 B1-3, S1-10BL 민간참여 공공주택사업(실시)',
      description: '해안,행림,피에이씨 공동 / 견적서 ECA-2505-2에서 전환',
      contract_start_date: '2025-10-01',
      contract_end_date: '2027-09-30',
      contract_amount: 205000000,
      vat_amount: 20500000,
      total_amount: 225500000,
      received_amount: 0,
      remaining_amount: 225500000,
      progress: 'in_progress',
      progress_note: '승인 진행중 / VAT 별도',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-32',
      contract_code: 'AA25-32',
      client_company: '㈜범도시건축종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '포항시 항구동 주상복합 신축공사 에너지절약계획서 변경',
      description: '',
      contract_start_date: '2025-10-01',
      contract_end_date: '2026-03-31',
      contract_amount: 3500000,
      vat_amount: 0,
      total_amount: 3500000,
      received_amount: 0,
      remaining_amount: 3500000,
      progress: 'in_progress',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-33',
      contract_code: 'AA25-33',
      client_company: '케이디건축종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '대전죽동2 A2BL 공동주택 친환경 컨설팅',
      description: '',
      contract_start_date: '2025-10-01',
      contract_end_date: '2026-09-30',
      contract_amount: 110000000,
      vat_amount: 0,
      total_amount: 110000000,
      received_amount: 0,
      remaining_amount: 110000000,
      progress: 'in_progress',
      progress_note: '승인 진행중 / 면세',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-34',
      contract_code: 'AA25-34',
      client_company: '㈜희림종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '검단신도시 AA17블록 중흥에스클래스 친환경+교육환경+녹색건축인증',
      description: '',
      contract_start_date: '2025-11-01',
      contract_end_date: '2026-10-31',
      contract_amount: 78030000,
      vat_amount: 0,
      total_amount: 78030000,
      received_amount: 0,
      remaining_amount: 78030000,
      progress: 'contract_signed',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-35',
      contract_code: 'AA25-35',
      client_company: '에이앤유디자인그룹건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '여수죽림 A7블록 친환경 컨설팅 (추가분)',
      description: '',
      contract_start_date: '2025-12-01',
      contract_end_date: '2026-11-30',
      contract_amount: 160000000,
      vat_amount: 0,
      total_amount: 160000000,
      received_amount: 0,
      remaining_amount: 160000000,
      progress: 'contract_signed',
      progress_note: '',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AA25-36',
      contract_code: 'AA25-36',
      client_company: '㈜해마종합건축사사무소',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'service',
      service_name: '(가칭)검단7초등학교 신축공사 설계용역',
      description: '',
      contract_start_date: '2025-12-01',
      contract_end_date: '2026-11-30',
      contract_amount: 25000000,
      vat_amount: 0,
      total_amount: 25000000,
      received_amount: 0,
      remaining_amount: 25000000,
      progress: 'contract_signed',
      progress_note: 'VAT 포함',
      notes: '',
      created_by: null,
    },
    // === 본인증 계약 (AB25) ===
    {
      company_id: companyId,
      contract_number: 'AB25-01',
      contract_code: 'AB25-01',
      client_company: '금호건설(주)',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'consulting',
      service_name: '야탑동 공공분양주택 신축공사 본인증 컨설팅',
      description: '',
      contract_start_date: '2025-02-01',
      contract_end_date: '2025-12-31',
      contract_amount: 31000000,
      vat_amount: 3100000,
      total_amount: 34100000,
      received_amount: 34100000,
      remaining_amount: 0,
      progress: 'completed',
      progress_note: '본(완)',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AB25-02',
      contract_code: 'AB25-02',
      client_company: '㈜마메종',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'consulting',
      service_name: '울산대공원 한신더휴 본인증 컨설팅',
      description: '',
      contract_start_date: '2025-04-01',
      contract_end_date: '2026-03-31',
      contract_amount: 38000000,
      vat_amount: 3800000,
      total_amount: 41800000,
      received_amount: 0,
      remaining_amount: 41800000,
      progress: 'in_progress',
      progress_note: '',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AB25-03',
      contract_code: 'AB25-03',
      client_company: '운정신도시대우케이원18호',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'consulting',
      service_name: '파주운정3 A-8블럭 공동주택 본인증 컨설팅',
      description: '',
      contract_start_date: '2025-08-01',
      contract_end_date: '2026-07-31',
      contract_amount: 50000000,
      vat_amount: 5000000,
      total_amount: 55000000,
      received_amount: 0,
      remaining_amount: 55000000,
      progress: 'in_progress',
      progress_note: '',
      notes: '미수금 21,000,000',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AB25-04',
      contract_code: 'AB25-04',
      client_company: '주식회사운정신도시대우케이원18호',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'consulting',
      service_name: '파주운정3 A-8블럭 공동주택 본인증 컨설팅(추가분)',
      description: '',
      contract_start_date: '2025-08-01',
      contract_end_date: '2026-07-31',
      contract_amount: 21000000,
      vat_amount: 2100000,
      total_amount: 23100000,
      received_amount: 0,
      remaining_amount: 23100000,
      progress: 'in_progress',
      progress_note: '',
      notes: '',
      created_by: null,
    },
    {
      company_id: companyId,
      contract_number: 'AB25-05',
      contract_code: 'AB25-05',
      client_company: '한진중공업',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'consulting',
      service_name: '남양주진접2 A-3BL 아파트 건설공사 녹색 및 에너지 본인증',
      description: '',
      contract_start_date: '2025-11-01',
      contract_end_date: '2026-10-31',
      contract_amount: 24500000,
      vat_amount: 0,
      total_amount: 24500000,
      received_amount: 0,
      remaining_amount: 24500000,
      progress: 'contract_signed',
      progress_note: '',
      notes: '',
      created_by: null,
    },
    // === 건설환경연구소 계약 (BB25) ===
    {
      company_id: companyId,
      contract_number: 'BB25-01',
      contract_code: 'BB25-01',
      client_company: '광명 제4R구역 주택재개발 정비사업 조합',
      client_business_number: '',
      client_contact_name: '',
      client_contact_phone: '',
      client_contact_email: '',
      contract_type: 'consulting',
      service_name: '광명 제4R구역 주택재개발 정비사업 본인증 용역',
      description: '건설환경연구소',
      contract_start_date: '2025-04-01',
      contract_end_date: '2026-03-31',
      contract_amount: 38770000,
      vat_amount: 0,
      total_amount: 38770000,
      received_amount: 0,
      remaining_amount: 38770000,
      progress: 'in_progress',
      progress_note: '',
      notes: '건설환경연구소 계약',
      created_by: null,
    },
  ];

  // 2019-2024 계약 데이터 (allContracts.json에서 변환)
  const yearCounters: Record<number, number> = {};
  const historicalContracts = allContractsRaw
    .filter(r => r.year < 2025)
    .map(r => {
      if (!yearCounters[r.year]) yearCounters[r.year] = 0;
      yearCounters[r.year]++;
      const seq = String(yearCounters[r.year]).padStart(3, '0');
      const yearStr = String(r.year).slice(2);
      const contractNumber = `EC${yearStr}-${seq}`;

      const contractAmount = Math.round(r.contract_amount || 0);
      const totalReceived = Math.round(r.total_received || 0);
      const remaining = Math.max(0, contractAmount - totalReceived);

      // 진행상태 결정
      let progress = 'completed';
      if (r.outstanding_invoiced > 0 || r.uninvoiced > 0) {
        progress = totalReceived > 0 ? 'in_progress' : 'contract_signed';
      } else if (totalReceived === 0 && contractAmount > 0) {
        // 수금액이 0인데 미수금도 0이면 → 면세/특수 케이스, 완료 처리
        progress = 'completed';
      }

      // 용역종류 자동 분류
      const categoryKeywords: Array<[string, string[]]> = [
        ['apartment', ['공동주택', '아파트']],
        ['public_housing', ['공공주택']],
        ['private_rental', ['민간임대', '임대주택']],
        ['happy_housing', ['행복주택']],
        ['mixed_use', ['주상복합']],
        ['officetel', ['오피스텔']],
        ['residential_improvement', ['주거환경개선', '주거환경 개선']],
        ['urban_development', ['도시개발']],
        ['redevelopment', ['재개발', '정비사업', '재건축']],
        ['knowledge_industry', ['지식산업', '산업단지', '산업센터']],
        ['educational', ['초등학교', '중학교', '고등학교', '학교', '교육시설']],
      ];
      let serviceCategory = 'other';
      for (const [value, keywords] of categoryKeywords) {
        if (keywords.some(kw => r.service.includes(kw))) {
          serviceCategory = value;
          break;
        }
      }

      return {
        company_id: companyId,
        contract_number: contractNumber,
        contract_code: contractNumber,
        client_company: r.company,
        client_business_number: '',
        client_contact_name: '',
        client_contact_phone: '',
        client_contact_email: '',
        contract_type: 'service',
        service_category: serviceCategory,
        service_name: r.service,
        description: r.notes || '',
        contract_start_date: `${r.year}-01-01`,
        contract_end_date: `${r.year}-12-31`,
        contract_amount: contractAmount,
        vat_amount: 0,
        total_amount: contractAmount,
        received_amount: totalReceived,
        remaining_amount: remaining,
        progress,
        progress_note: '',
        notes: '',
        created_by: null,
      };
    });

  return [...contracts2025, ...historicalContracts];
}

// ================================================================
// 입금 내역
// ================================================================
export function getSamplePayments(contracts: any[]) {
  const payments: any[] = [];
  const findContract = (num: string) => contracts.find((c: any) => c.contract_number === num);

  // 2025년 수작업 입금 내역
  const aa2501 = findContract('AA25-01');
  if (aa2501) {
    payments.push({
      contract_id: aa2501.id,
      amount: 13200000,
      payment_date: '2025-01-15',
      payment_type: 'advance',
      description: '착수금',
    });
  }

  const aa2506 = findContract('AA25-06');
  if (aa2506) {
    payments.push({
      contract_id: aa2506.id,
      amount: 27600000,
      payment_date: '2025-05-10',
      payment_type: 'advance',
      description: '1차 기성',
    });
  }

  const aa2513 = findContract('AA25-13');
  if (aa2513) {
    payments.push({
      contract_id: aa2513.id,
      amount: 25000000,
      payment_date: '2025-08-20',
      payment_type: 'advance',
      description: '착수금',
    });
  }

  const aa2522 = findContract('AA25-22');
  if (aa2522) {
    payments.push({
      contract_id: aa2522.id,
      amount: 33200000,
      payment_date: '2025-10-15',
      payment_type: 'progress',
      description: '1차 기성',
    });
  }

  const ab2501 = findContract('AB25-01');
  if (ab2501) {
    payments.push(
      {
        contract_id: ab2501.id,
        amount: 17050000,
        payment_date: '2025-03-10',
        payment_type: 'advance',
        description: '선금 50%',
      },
      {
        contract_id: ab2501.id,
        amount: 17050000,
        payment_date: '2025-11-20',
        payment_type: 'final',
        description: '잔금 50%',
      }
    );
  }

  // 2019-2024 계약의 입금 내역 (JSON 데이터에서 변환)
  const yearCounters: Record<number, number> = {};
  for (const raw of allContractsRaw) {
    if (raw.year >= 2025) continue;
    if (!raw.payments || raw.payments.length === 0) continue;

    // 계약 번호 재생성 (getSampleContracts와 동일한 로직)
    if (!yearCounters[raw.year]) yearCounters[raw.year] = 0;
    yearCounters[raw.year]++;
    const seq = String(yearCounters[raw.year]).padStart(3, '0');
    const yearStr = String(raw.year).slice(2);
    const contractNumber = `EC${yearStr}-${seq}`;

    const contract = findContract(contractNumber);
    if (!contract) continue;

    for (let i = 0; i < raw.payments.length; i++) {
      const p = raw.payments[i];
      const paymentAmount = Math.round(p.payment_amount || 0);
      if (paymentAmount <= 0) continue;

      payments.push({
        contract_id: contract.id,
        amount: paymentAmount,
        payment_date: p.payment_date || p.invoice_date,
        payment_type: i === 0 ? 'advance' : i === raw.payments.length - 1 ? 'final' : 'progress',
        description: `${i + 1}차 기성 (청구: ${p.invoice_date || ''})`,
      });
    }
  }

  return payments;
}

// ================================================================
// 변경 이력
// ================================================================
export function getSampleHistories(contracts: any[]) {
  const histories: any[] = [];
  const findContract = (num: string) => contracts.find((c: any) => c.contract_number === num);

  const aa2501 = findContract('AA25-01');
  if (aa2501) {
    histories.push({
      contract_id: aa2501.id,
      change_type: 'progress',
      old_value: 'contract_signed',
      new_value: 'in_progress',
      changed_by: null,
      note: '승인(완), 변경승인 진행중',
    });
  }

  const ab2501 = findContract('AB25-01');
  if (ab2501) {
    histories.push({
      contract_id: ab2501.id,
      change_type: 'progress',
      old_value: 'in_progress',
      new_value: 'completed',
      changed_by: null,
      note: '본인증 완료',
    });
  }

  const aa2513 = findContract('AA25-13');
  if (aa2513) {
    histories.push({
      contract_id: aa2513.id,
      change_type: 'created',
      old_value: null,
      new_value: 'contract_signed',
      changed_by: null,
      note: '2025년 최대 규모 계약 체결 (250,000,000원)',
    });
  }

  return histories;
}
